name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - gcc-14
        generator:
          - "Ninja Multi-Config"
        build_type:
          - Debug
        qt_host:
          - linux
        qt_arch:
          - linux_gcc_64

    steps:
      - name: Install dependencies
        run: sudo apt-get install -y libcurl4-openssl-dev libxcb-xinerama0 libxkbcommon-dev libxkbcommon-x11-dev

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Cache
        uses: ./.github/actions/setup_cache
        with:
          compiler: ${{ matrix.compiler }}
          build_type: ${{ matrix.build_type }}
          generator: ${{ matrix.generator }}

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: false
          cmake: true
          ninja: true
          vcpkg: false
          ccache: true
          clangtidy: false
          cppcheck: false
          gcovr: false
          opencppcoverage: false
          doxygen: false
          graphviz: false

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.8.0"
          host: ${{ matrix.qt_host }}
          target: "desktop"
          arch: ${{ matrix.qt_arch }}
          install-deps: "true"
          cache: "true"
          aqtversion: "==3.1.*"
          py7zrversion: "==0.20.*"

      - name: Install sonar-scanner and build-wrapper
        uses: SonarSource/sonarcloud-github-c-cpp@v3

      - name: Create Build Environment
        run: cmake -E make_directory ${{ runner.workspace }}/build

      - name: Configure CMake
        working-directory: ${{ runner.workspace }}/build
        run: |
          cmake -G "${{ matrix.generator }}" $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE:STRING=${{ matrix.build_type }} -DENABLE_DOCS:BOOL=FALSE -DCOMPILE_TESTS:BOOL=FALSE -DENABLE_CLANG_TIDY:BOOL=FALSE -DENABLE_CPPCHECK:BOOL=FALSE -DENABLE_INCLUDE_WHAT_YOU_USE:BOOL=FALSE

      - name: Build
        working-directory: ${{ runner.workspace }}/build
        run: cmake --build . --parallel ${{ env.nproc }} --config ${{ matrix.build_type }}

      - name: Run sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner --define sonar.cfamily.compile-commands="${{ runner.workspace }}/build/compile_commands.json"
